apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: default
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      hostname: test-mongodb
      containers:
      - name: database
        image: mongo:latest
        imagePullPolicy: Always
        env:
        - name: MONGO_INITDB_DATABASE
          value: "userdb"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "pass"
        ports:
        - containerPort: 27017
