apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
  - port: 3002
    protocol: TCP
    targetPort: 3002

